// PLACEHOLDER CONTENT IN THIS MIGRATION
// The seed inserts below produce dev/demo data clearly flagged with is_placeholder = 1.
// When the content team delivers the real prompt library, write a 0002 migration that
// DELETEs WHERE is_placeholder = 1 and INSERTs the real content. Do not edit this file.

import * as SQLite from 'expo-sqlite';

const SCHEMA = `
  CREATE TABLE categories (
    id             TEXT PRIMARY KEY,
    name           TEXT NOT NULL,
    description    TEXT,
    display_order  INTEGER NOT NULL DEFAULT 0,
    icon           TEXT,
    is_placeholder INTEGER NOT NULL DEFAULT 0
  );

  CREATE TABLE tags (
    id             TEXT PRIMARY KEY,
    category_id    TEXT REFERENCES categories(id),
    label          TEXT NOT NULL,
    is_placeholder INTEGER NOT NULL DEFAULT 0
  );

  CREATE TABLE liminal_spaces (
    id             TEXT PRIMARY KEY,
    name           TEXT NOT NULL,
    description    TEXT,
    icon           TEXT,
    display_order  INTEGER NOT NULL DEFAULT 0,
    is_placeholder INTEGER NOT NULL DEFAULT 0
  );

  CREATE TABLE prompts (
    id             TEXT PRIMARY KEY,
    age_group      TEXT NOT NULL,
    category_id    TEXT REFERENCES categories(id),
    text           TEXT NOT NULL,
    full_question  TEXT NOT NULL DEFAULT 'What are all the things you can think of that you could do?',
    tier           TEXT NOT NULL DEFAULT 'free' CHECK (tier IN ('free','premium','professional')),
    source         TEXT NOT NULL DEFAULT 'official',
    liminal_space  TEXT REFERENCES liminal_spaces(id),
    parent_askable INTEGER NOT NULL DEFAULT 0,
    is_active      INTEGER NOT NULL DEFAULT 1,
    is_placeholder INTEGER NOT NULL DEFAULT 0,
    created_at     TEXT NOT NULL,
    updated_at     TEXT NOT NULL
  );

  CREATE INDEX idx_prompts_age_group ON prompts(age_group, is_active);
  CREATE INDEX idx_prompts_category ON prompts(category_id);
  CREATE INDEX idx_prompts_liminal_space ON prompts(liminal_space);

  CREATE TABLE prompt_tags (
    prompt_id TEXT NOT NULL REFERENCES prompts(id) ON DELETE CASCADE,
    tag_id    TEXT NOT NULL REFERENCES tags(id) ON DELETE CASCADE,
    PRIMARY KEY (prompt_id, tag_id)
  );

  CREATE TABLE tips (
    id             TEXT PRIMARY KEY,
    prompt_id      TEXT REFERENCES prompts(id) ON DELETE CASCADE,
    kind           TEXT NOT NULL CHECK (kind IN ('kickstarter','discussion','follow_up','safety_note')),
    body           TEXT NOT NULL,
    audience       TEXT NOT NULL DEFAULT 'adult' CHECK (audience IN ('adult','child','either')),
    display_order  INTEGER NOT NULL DEFAULT 0,
    is_placeholder INTEGER NOT NULL DEFAULT 0
  );

  CREATE INDEX idx_tips_prompt ON tips(prompt_id);

  CREATE TABLE world_building (
    id             TEXT PRIMARY KEY,
    prompt_id      TEXT NOT NULL REFERENCES prompts(id) ON DELETE CASCADE,
    card_text      TEXT NOT NULL,
    display_order  INTEGER NOT NULL DEFAULT 0,
    difficulty     INTEGER NOT NULL DEFAULT 1,
    is_placeholder INTEGER NOT NULL DEFAULT 0
  );

  CREATE INDEX idx_world_building_prompt ON world_building(prompt_id);

  CREATE TABLE contexts (
    id                  TEXT PRIMARY KEY,
    label               TEXT NOT NULL,
    age_group_default   TEXT,
    is_anonymous        INTEGER NOT NULL DEFAULT 0,
    color_token         TEXT,
    created_at          TEXT NOT NULL,
    archived_at         TEXT
  );

  CREATE TABLE favorites (
    context_id   TEXT NOT NULL REFERENCES contexts(id) ON DELETE CASCADE,
    prompt_id    TEXT NOT NULL REFERENCES prompts(id) ON DELETE CASCADE,
    favorited_at TEXT NOT NULL,
    PRIMARY KEY (context_id, prompt_id)
  );

  CREATE INDEX idx_favorites_context ON favorites(context_id);

  CREATE TABLE reflections (
    id         TEXT PRIMARY KEY,
    context_id TEXT NOT NULL REFERENCES contexts(id) ON DELETE CASCADE,
    prompt_id  TEXT NOT NULL REFERENCES prompts(id),
    note       TEXT,
    audio_uri  TEXT,
    rating     INTEGER,
    created_at TEXT NOT NULL
  );

  CREATE INDEX idx_reflections_context_prompt ON reflections(context_id, prompt_id);

  CREATE TABLE personalization (
    context_id TEXT NOT NULL REFERENCES contexts(id) ON DELETE CASCADE,
    key        TEXT NOT NULL,
    value      TEXT NOT NULL,
    PRIMARY KEY (context_id, key)
  );

  CREATE TABLE modules (
    id             TEXT PRIMARY KEY,
    title          TEXT NOT NULL,
    description    TEXT,
    age_group      TEXT,
    category_id    TEXT REFERENCES categories(id),
    duration_days  INTEGER NOT NULL DEFAULT 5,
    tier           TEXT NOT NULL DEFAULT 'free',
    cover_color    TEXT,
    display_order  INTEGER NOT NULL DEFAULT 0,
    is_placeholder INTEGER NOT NULL DEFAULT 0
  );

  CREATE TABLE module_steps (
    module_id   TEXT NOT NULL REFERENCES modules(id) ON DELETE CASCADE,
    step_number INTEGER NOT NULL,
    prompt_id   TEXT NOT NULL REFERENCES prompts(id),
    intro_text  TEXT,
    outro_text  TEXT,
    PRIMARY KEY (module_id, step_number)
  );

  CREATE TABLE module_progress (
    context_id   TEXT NOT NULL REFERENCES contexts(id) ON DELETE CASCADE,
    module_id    TEXT NOT NULL REFERENCES modules(id) ON DELETE CASCADE,
    prompt_id    TEXT NOT NULL REFERENCES prompts(id),
    completed_at TEXT,
    PRIMARY KEY (context_id, module_id, prompt_id)
  );
`;

// --- Placeholder seed content (clearly flagged with is_placeholder = 1) ---

const placeholderPrompts: Array<{
  id: string;
  ageGroup: '3-5' | '6-8' | '9-12' | '13-15';
  text: string;
  category: string;
  liminalSpace: string | null;
}> = [
  // 3-5
  { id: 'ph-3-5-001', ageGroup: '3-5', text: 'What if you really want a toy that another kid is playing with? What could you do?', category: 'cat-ethics', liminalSpace: null },
  { id: 'ph-3-5-002', ageGroup: '3-5', text: 'What if you accidentally spill your juice on the floor? What could you do?', category: 'cat-ethics', liminalSpace: 'ls-mealtime' },
  { id: 'ph-3-5-003', ageGroup: '3-5', text: 'What if you feel scared at bedtime? What could you do?', category: 'cat-emotions', liminalSpace: 'ls-bedtime' },
  // 6-8
  { id: 'ph-6-8-001', ageGroup: '6-8', text: 'What if you see someone being mean to the new student? What could you do?', category: 'cat-ethics', liminalSpace: null },
  { id: 'ph-6-8-002', ageGroup: '6-8', text: 'What if you break something that belongs to a friend? What could you do?', category: 'cat-ethics', liminalSpace: null },
  { id: 'ph-6-8-003', ageGroup: '6-8', text: "What if you're feeling left out at recess? What could you do?", category: 'cat-emotions', liminalSpace: null },
  // 9-12
  { id: 'ph-9-12-001', ageGroup: '9-12', text: 'What if your friend asks you to lie to their parents? What could you do?', category: 'cat-ethics', liminalSpace: null },
  { id: 'ph-9-12-002', ageGroup: '9-12', text: 'What if you see someone cheating on a test? What could you do?', category: 'cat-ethics', liminalSpace: null },
  { id: 'ph-9-12-003', ageGroup: '9-12', text: "What if you're struggling with homework but afraid to ask for help? What could you do?", category: 'cat-emotions', liminalSpace: null },
  // 13-15
  { id: 'ph-13-15-001', ageGroup: '13-15', text: "What if your friends pressure you to do something you're uncomfortable with? What could you do?", category: 'cat-ethics', liminalSpace: null },
  { id: 'ph-13-15-002', ageGroup: '13-15', text: 'What if you discover a friend is being bullied online? What could you do?', category: 'cat-ethics', liminalSpace: null },
  { id: 'ph-13-15-003', ageGroup: '13-15', text: 'What if you disagree strongly with something your parents decided? What could you do?', category: 'cat-emotions', liminalSpace: 'ls-car-ride' },
];

const placeholderTipsPerPrompt: Array<{ kind: 'kickstarter' | 'discussion' | 'follow_up'; body: string }> = [
  { kind: 'kickstarter', body: '[PLACEHOLDER] Try opening with: "I wonder what you\'d do..."' },
  { kind: 'discussion',  body: '[PLACEHOLDER] Listen for feelings underneath the answer.' },
  { kind: 'follow_up',   body: '[PLACEHOLDER] Ask: "What else could someone try?"' },
];

const placeholderWorldBuilding: Record<string, string[]> = {
  'ph-3-5-001': [
    '[PLACEHOLDER] What if it was your favorite toy?',
    '[PLACEHOLDER] What if the other kid was your best friend?',
  ],
  'ph-6-8-001': [
    '[PLACEHOLDER] What if no one else saw it happen?',
    '[PLACEHOLDER] What if the new student was your sibling?',
  ],
  'ph-9-12-001': [
    '[PLACEHOLDER] What if it was just a small lie?',
    '[PLACEHOLDER] What if the parents would find out anyway?',
  ],
  'ph-13-15-001': [
    '[PLACEHOLDER] What if everyone else in the group was already doing it?',
    '[PLACEHOLDER] What if saying no meant losing the friend group?',
  ],
};

async function seedPlaceholders(db: SQLite.SQLiteDatabase, now: string): Promise<void> {
  // Categories
  const categories = [
    { id: 'cat-ethics',    name: 'Ethics',    order: 1, icon: 'compass' },
    { id: 'cat-emotions',  name: 'Emotions',  order: 2, icon: 'heart' },
    { id: 'cat-fun',       name: 'Fun & Imagination', order: 3, icon: 'star' },
    { id: 'cat-school',    name: 'School Connection', order: 4, icon: 'book-open' },
  ];
  for (const c of categories) {
    await db.runAsync(
      'INSERT INTO categories (id, name, display_order, icon, is_placeholder) VALUES (?, ?, ?, ?, 1)',
      c.id, c.name, c.order, c.icon
    );
  }

  // Liminal spaces
  const spaces = [
    { id: 'ls-car-ride',     name: 'Car Ride',     icon: 'truck',     order: 1 },
    { id: 'ls-bedtime',      name: 'Bedtime',      icon: 'moon',      order: 2 },
    { id: 'ls-mealtime',     name: 'Mealtime',     icon: 'coffee',    order: 3 },
    { id: 'ls-waiting-room', name: 'Waiting Room', icon: 'clock',     order: 4 },
  ];
  for (const s of spaces) {
    await db.runAsync(
      'INSERT INTO liminal_spaces (id, name, icon, display_order, is_placeholder) VALUES (?, ?, ?, ?, 1)',
      s.id, s.name, s.icon, s.order
    );
  }

  // Prompts + per-prompt tips + world-building
  for (const p of placeholderPrompts) {
    await db.runAsync(
      `INSERT INTO prompts
       (id, age_group, category_id, text, tier, source, liminal_space, parent_askable, is_active, is_placeholder, created_at, updated_at)
       VALUES (?, ?, ?, ?, 'free', 'official', ?, 1, 1, 1, ?, ?)`,
      p.id, p.ageGroup, p.category, p.text, p.liminalSpace, now, now
    );

    let tipOrder = 0;
    for (const t of placeholderTipsPerPrompt) {
      await db.runAsync(
        'INSERT INTO tips (id, prompt_id, kind, body, audience, display_order, is_placeholder) VALUES (?, ?, ?, ?, ?, ?, 1)',
        `${p.id}-tip-${tipOrder}`, p.id, t.kind, t.body, 'adult', tipOrder
      );
      tipOrder++;
    }

    const cards = placeholderWorldBuilding[p.id];
    if (cards) {
      let cardOrder = 0;
      for (const text of cards) {
        await db.runAsync(
          'INSERT INTO world_building (id, prompt_id, card_text, display_order, difficulty, is_placeholder) VALUES (?, ?, ?, ?, ?, 1)',
          `${p.id}-wb-${cardOrder}`, p.id, text, cardOrder, 1
        );
        cardOrder++;
      }
    }
  }

  // Default Quick Start context (created here so first launch lands on a usable state)
  await db.runAsync(
    'INSERT INTO contexts (id, label, age_group_default, is_anonymous, color_token, created_at) VALUES (?, ?, ?, 0, ?, ?)',
    'ctx-quick-start', 'Quick Start', null, '#90dcff', now
  );
}

export const migration_0001_init = {
  name: '0001_init',
  async up(db: SQLite.SQLiteDatabase): Promise<void> {
    await db.execAsync(SCHEMA);
    const now = new Date().toISOString();
    await seedPlaceholders(db, now);
  },
};
